name: Check Friend Links Task

on:
  schedule:
    # 每 12 小时运行一次
    - cron: '0 */12 * * *'
  workflow_dispatch: # 允许手动触发
jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码到 results 分支
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run friend links checker
        run: python scripts/frlink-check.py -f src/data/friend-links.yaml -o scripts/result/result.json

      - name: Push results to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: ed333a/ed333a.github.io 
          publish_branch: main
          publish_dir: ./scripts/result
          keep_files: true